$origDebugPreference = $DebugPreference
$DebugPreference = "Continue"

$origWorkingDirectory = Get-Location

$RepoRootPath = "C:\_Flexjet"
$APIRepoPath = $RepoRootPath + "\Repos-API"
$DBRepoPath = $RepoRootPath + "\Repos-DB"
$WebRepoPath = $RepoRootPath + "\Repos-Web"
$TaskRepoPath = $RepoRootPath + "\Repos-Task"
$CommonRepoPath = $RepoRootPath + "\Repos-Common"
$ProducerComsumersRepoPath = $RepoRootPath + "\Repos-ProducersConsumers"
$OtherRepoPath = $RepoRootPath + "\Repos-Other"
$TestRepoPath = $RepoRootPath + "\Repos-API-Test"

$sentientSyncDBConnString = "Server=DEVSentientSQL.flexjetnet.com;Database=SentientSync;Integrated Security=true;Multisubnetfailover=yes;Application Name=Skynet.Powershell-Dev;Encrypt=false"
$sentientProdDBConnString = "Server=DEVSentientSQL.flexjetnet.com;Database=Prod;Integrated Security=true;Multisubnetfailover=yes;Application Name=Skynet.Powershell-Dev;Encrypt=false"
$AircraftDBConnString = "Server=DEVAircraftSQL.onesky.com;Database=Aircraft;Integrated Security=true;Multisubnetfailover=yes;Application Name=Skynet.Powershell-Dev;Encrypt=false"

$testJson1 = @"
{
    "result": {
      "data": {
        "data": [
          {
            "flightInfoEx": {
              "next_offsetField": 10,
              "flightsField": [
                {
                  "faFlightIDField": "LXJ430-1687292631-sw-1007p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "01:46:00",
                  "filed_timeField": 1687357125,
                  "filed_departuretimeField": 1687354920,
                  "filed_airspeed_ktsField": 433,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 430,
                  "routeField": "ROZBO5ROZBOSLITTSMPRRELMSZQ97DEBRLCSTAL2",
                  "actualdeparturetimeField": 1687357091,
                  "estimatedarrivaltimeField": 1687370204,
                  "actualarrivaltimeField": 0,
                  "divertedField": "",
                  "originField": "KRDU",
                  "destinationField": "TAPA",
                  "originNameField": "Raleigh-DurhamIntl",
                  "originCityField": "Raleigh/Durham,NC",
                  "destinationNameField": "VCBirdInt'l",
                  "destinationCityField": "SaintJohn's,Antigua"
                },
                {
                  "faFlightIDField": "LXJ430-1687292631-sw-1007p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "01:46:00",
                  "filed_timeField": 1687357125,
                  "filed_departuretimeField": 1687354920,
                  "filed_airspeed_ktsField": 433,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 430,
                  "routeField": "ROZBO5ROZBOSLITTSMPRRELMSZQ97DEBRLCSTAL2",
                  "actualdeparturetimeField": -1,
                  "estimatedarrivaltimeField": -1,
                  "actualarrivaltimeField": -1,
                  "divertedField": "t",
                  "originField": "KRDU",
                  "destinationField": "07FA",
                  "originNameField": "Raleigh-DurhamIntl",
                  "originCityField": "Raleigh/Durham,NC",
                  "destinationNameField": "OceanReefClub",
                  "destinationCityField": "KeyLargo,FL"
                },
                {
                  "faFlightIDField": "LXJ430-1687336560-sw-1069p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "03:46:00",
                  "filed_timeField": 1687353960,
                  "filed_departuretimeField": 1687354920,
                  "filed_airspeed_ktsField": 427,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 410,
                  "routeField": "RDU195049OKNEECLOWRY327JAINSL451LETONL451IORIOL451JORGGKNDLLVERMOGUYROANU",
                  "actualdeparturetimeField": 0,
                  "estimatedarrivaltimeField": 1687370655,
                  "actualarrivaltimeField": 0,
                  "divertedField": "",
                  "originField": "KRDU",
                  "destinationField": "TAPA",
                  "originNameField": "Raleigh-DurhamIntl",
                  "originCityField": "Raleigh/Durham,NC",
                  "destinationNameField": "VCBirdInt'l",
                  "destinationCityField": "SaintJohn's,Antigua"
                },
                {
                  "faFlightIDField": "LXJ430-1687209029-sw-1033p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "02:21:00",
                  "filed_timeField": 1687264473,
                  "filed_departuretimeField": 1687266000,
                  "filed_airspeed_ktsField": 439,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 450,
                  "routeField": "EARTURCKROEZZROCKYGBEESBKWTIVAEALDAN3",
                  "actualdeparturetimeField": 1687269861,
                  "estimatedarrivaltimeField": 1687279172,
                  "actualarrivaltimeField": 1687279172,
                  "divertedField": "",
                  "originField": "KEAR",
                  "destinationField": "KRDU",
                  "originNameField": "KearneyRgnl",
                  "originCityField": "Kearney,NE",
                  "destinationNameField": "Raleigh-DurhamIntl",
                  "destinationCityField": "Raleigh/Durham,NC"
                },
                {
                  "faFlightIDField": "LXJ430-1687202075-sw-386p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "00:53:00",
                  "filed_timeField": 1687213842,
                  "filed_departuretimeField": 1687215420,
                  "filed_airspeed_ktsField": 453,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 320,
                  "routeField": "TULV73FRAKSSLNHSI",
                  "actualdeparturetimeField": 1687217264,
                  "estimatedarrivaltimeField": 1687220448,
                  "actualarrivaltimeField": 1687220448,
                  "divertedField": "",
                  "originField": "KTUL",
                  "destinationField": "KEAR",
                  "originNameField": "TulsaIntl",
                  "originCityField": "Tulsa,OK",
                  "destinationNameField": "KearneyRgnl",
                  "destinationCityField": "Kearney,NE"
                },
                {
                  "faFlightIDField": "LXJ430-1687194924-sw-498p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "01:11:00",
                  "filed_timeField": 1687204894,
                  "filed_departuretimeField": 1687206600,
                  "filed_airspeed_ktsField": 470,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 400,
                  "routeField": "TALLOECIGEMAYJITUL",
                  "actualdeparturetimeField": 1687209884,
                  "estimatedarrivaltimeField": 1687214392,
                  "actualarrivaltimeField": 1687214392,
                  "divertedField": "",
                  "originField": "KHSV",
                  "destinationField": "KTUL",
                  "originNameField": "HuntsvilleIntl",
                  "originCityField": "Huntsville,AL",
                  "destinationNameField": "TulsaIntl",
                  "destinationCityField": "Tulsa,OK"
                },
                {
                  "faFlightIDField": "LXJ430-1687183303-sw-937p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "00:46:00",
                  "filed_timeField": 1687196584,
                  "filed_departuretimeField": 1687199220,
                  "filed_airspeed_ktsField": 461,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 280,
                  "routeField": "CHCLLFORKSRQZ",
                  "actualdeparturetimeField": -1,
                  "estimatedarrivaltimeField": -1,
                  "actualarrivaltimeField": -1,
                  "divertedField": "",
                  "originField": "KLUK",
                  "destinationField": "KHSV",
                  "originNameField": "CincinnatiMuni",
                  "originCityField": "Cincinnati,OH",
                  "destinationNameField": "HuntsvilleIntl",
                  "destinationCityField": "Huntsville,AL"
                },
                {
                  "faFlightIDField": "LXJ430-1687196972-sw-96p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "00:49:00",
                  "filed_timeField": 1687197890,
                  "filed_departuretimeField": 1687199220,
                  "filed_airspeed_ktsField": 456,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 300,
                  "routeField": "CHCLL5IIURQZ",
                  "actualdeparturetimeField": 1687200987,
                  "estimatedarrivaltimeField": 1687204075,
                  "actualarrivaltimeField": 1687204075,
                  "divertedField": "",
                  "originField": "KCVG",
                  "destinationField": "KHSV",
                  "originNameField": "Cincinnati/NorthernKentuckyInternationalAirport",
                  "originCityField": "Hebron,KY",
                  "destinationNameField": "HuntsvilleIntl",
                  "destinationCityField": "Huntsville,AL"
                },
                {
                  "faFlightIDField": "LXJ430-1687153539-sw-1778p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "01:33:00",
                  "filed_timeField": 1687185669,
                  "filed_departuretimeField": 1687187700,
                  "filed_airspeed_ktsField": 446,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 450,
                  "routeField": "LBYMEIDEVACFORKSPETES",
                  "actualdeparturetimeField": 1687189431,
                  "estimatedarrivaltimeField": 1687195556,
                  "actualarrivaltimeField": 1687195556,
                  "divertedField": "",
                  "originField": "KMSY",
                  "destinationField": "KCVG",
                  "originNameField": "NewOrleansIntl",
                  "originCityField": "NewOrleans,LA",
                  "destinationNameField": "Cincinnati/NorthernKentuckyInternationalAirport",
                  "destinationCityField": "Hebron,KY"
                }
              ]
            },
            "aircraftType": {
              "manufacturerField": "Embraer",
              "typeField": "Legacy450",
              "descriptionField": "twin-jet"
            },
            "inFlightInfo": {
              "faFlightIDField": "LXJ430-1687292631-sw-1007p",
              "identField": "LXJ430",
              "prefixField": "",
              "typeField": "E545",
              "suffixField": "",
              "originField": "KRDU",
              "destinationField": "TAPA",
              "timeoutField": "ok",
              "timestampField": 1687362787,
              "departureTimeField": 1687357091,
              "firstPositionTimeField": 1687357091,
              "arrivalTimeField": 0,
              "longitudeField": -73.37406,
              "latitudeField": 27.19013,
              "lowLongitudeField": -79.15694,
              "lowLatitudeField": 27.19013,
              "highLongitudeField": -73.37406,
              "highLatitudeField": 35.9151,
              "groundspeedField": 425,
              "altitudeField": 410,
              "headingField": 131,
              "altitudeStatusField": "",
              "updateTypeField": "TP",
              "altitudeChangeField": "",
              "waypointsField": ""
            },
            "originAirportInfo": {
              "nameField": "Raleigh-DurhamIntl",
              "locationField": "Raleigh/Durham,NC",
              "longitudeField": -78.7874756,
              "latitudeField": 35.87764,
              "timezoneField": ":America/New_York"
            },
            "destinationAirportInfo": {
              "nameField": "VCBirdInt'l",
              "locationField": "SaintJohn's,Antigua",
              "longitudeField": -61.7926674,
              "latitudeField": 17.13675,
              "timezoneField": ":America/Antigua"
            }
          }
        ],
        "errors": []
      },
      "statusCode": 200,
      "errors": [],
      "warnings": []
    },
    "id": 1,
    "status": 5,
    "isCanceled": false,
    "isCompleted": true,
    "isCompletedSuccessfully": true,
    "creationOptions": 0,
    "isFaulted": false
  }'
"@

$testJson2 = @"
{
    "result": {
      "data": {
        "data": [
          {
            "flightInfoEx": {
              "next_offsetField": 10,
              "flightsField": [
                {
                  "faFlightIDField": "LXJ430-1687292631-sw-1007p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "01:47:00",
                  "filed_timeField": 1687357125,
                  "filed_departuretimeField": 1687354920,
                  "filed_airspeed_ktsField": 433,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 430,
                  "routeField": "ROZBO5ROZBOSLITTSMPRRELMSZQ97DEBRLCSTAL2",
                  "actualdeparturetimeField": 1687357091,
                  "estimatedarrivaltimeField": 1687370204,
                  "actualarrivaltimeField": 0,
                  "divertedField": "",
                  "originField": "KRDU",
                  "destinationField": "TAPA",
                  "originNameField": "Raleigh-DurhamIntl",
                  "originCityField": "Raleigh/Durham,NC",
                  "destinationNameField": "VCBirdInt'l",
                  "destinationCityField": "SaintJohn's,Antigua"
                },
                {
                  "faFlightIDField": "LXJ430-1687292631-sw-1007p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "01:46:00",
                  "filed_timeField": 1687357125,
                  "filed_departuretimeField": 1687354920,
                  "filed_airspeed_ktsField": 433,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 430,
                  "routeField": "ROZBO5ROZBOSLITTSMPRRELMSZQ97DEBRLCSTAL2",
                  "actualdeparturetimeField": -1,
                  "estimatedarrivaltimeField": -1,
                  "actualarrivaltimeField": -1,
                  "divertedField": "t",
                  "originField": "KRDU",
                  "destinationField": "07FA",
                  "originNameField": "Raleigh-DurhamIntl",
                  "originCityField": "Raleigh/Durham,NC",
                  "destinationNameField": "OceanReefClub",
                  "destinationCityField": "KeyLargo,FL"
                },
                {
                  "faFlightIDField": "LXJ430-1687336560-sw-1069p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "03:46:00",
                  "filed_timeField": 1687353960,
                  "filed_departuretimeField": 1687354920,
                  "filed_airspeed_ktsField": 427,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 410,
                  "routeField": "RDU195049OKNEECLOWRY327JAINSL451LETONL451IORIOL451JORGGKNDLLVERMOGUYROANU",
                  "actualdeparturetimeField": 0,
                  "estimatedarrivaltimeField": 1687370655,
                  "actualarrivaltimeField": 0,
                  "divertedField": "",
                  "originField": "KRDU",
                  "destinationField": "TAPA",
                  "originNameField": "Raleigh-DurhamIntl",
                  "originCityField": "Raleigh/Durham,NC",
                  "destinationNameField": "VCBirdInt'l",
                  "destinationCityField": "SaintJohn's,Antigua"
                },
                {
                  "faFlightIDField": "LXJ430-1687209029-sw-1033p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "02:21:00",
                  "filed_timeField": 1687264473,
                  "filed_departuretimeField": 1687266000,
                  "filed_airspeed_ktsField": 439,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 450,
                  "routeField": "EARTURCKROEZZROCKYGBEESBKWTIVAEALDAN3",
                  "actualdeparturetimeField": 1687269861,
                  "estimatedarrivaltimeField": 1687279172,
                  "actualarrivaltimeField": 1687279172,
                  "divertedField": "",
                  "originField": "KEAR",
                  "destinationField": "KRDU",
                  "originNameField": "KearneyRgnl",
                  "originCityField": "Kearney,NE",
                  "destinationNameField": "Raleigh-DurhamIntl",
                  "destinationCityField": "Raleigh/Durham,NC"
                },
                {
                  "faFlightIDField": "LXJ430-1687202075-sw-386p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "00:53:00",
                  "filed_timeField": 1687213842,
                  "filed_departuretimeField": 1687215420,
                  "filed_airspeed_ktsField": 453,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 320,
                  "routeField": "TULV73FRAKSSLNHSI",
                  "actualdeparturetimeField": 1687217264,
                  "estimatedarrivaltimeField": 1687220448,
                  "actualarrivaltimeField": 1687220448,
                  "divertedField": "",
                  "originField": "KTUL",
                  "destinationField": "KEAR",
                  "originNameField": "TulsaIntl",
                  "originCityField": "Tulsa,OK",
                  "destinationNameField": "KearneyRgnl",
                  "destinationCityField": "Kearney,NE"
                },
                {
                  "faFlightIDField": "LXJ430-1687194924-sw-498p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "01:14:00",
                  "filed_timeField": 1687204894,
                  "filed_departuretimeField": 1687206600,
                  "filed_airspeed_ktsField": 470,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 400,
                  "routeField": "TALLOECIGEMAYJITUL",
                  "actualdeparturetimeField": 1687209884,
                  "estimatedarrivaltimeField": 1687214392,
                  "actualarrivaltimeField": 1687214392,
                  "divertedField": "",
                  "originField": "KHSV",
                  "destinationField": "KTUL",
                  "originNameField": "HuntsvilleIntl",
                  "originCityField": "Huntsville,AL",
                  "destinationNameField": "TulsaIntl",
                  "destinationCityField": "Tulsa,OK"
                },
                {
                  "faFlightIDField": "LXJ430-1687183303-sw-937p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "00:46:00",
                  "filed_timeField": 1687196584,
                  "filed_departuretimeField": 1687199220,
                  "filed_airspeed_ktsField": 461,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 280,
                  "routeField": "CHCLLFORKSRQZ",
                  "actualdeparturetimeField": -1,
                  "estimatedarrivaltimeField": -1,
                  "actualarrivaltimeField": -1,
                  "divertedField": "",
                  "originField": "KLUK",
                  "destinationField": "KHSV",
                  "originNameField": "CincinnatiMuni",
                  "originCityField": "Cincinnati,OH",
                  "destinationNameField": "HuntsvilleIntl",
                  "destinationCityField": "Huntsville,AL"
                },
                {
                  "faFlightIDField": "LXJ430-1687196972-sw-96p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "00:49:00",
                  "filed_timeField": 1687197890,
                  "filed_departuretimeField": 1687199220,
                  "filed_airspeed_ktsField": 456,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 300,
                  "routeField": "CHCLL5IIURQZ",
                  "actualdeparturetimeField": 1687200987,
                  "estimatedarrivaltimeField": 1687204075,
                  "actualarrivaltimeField": 1687204075,
                  "divertedField": "",
                  "originField": "KCVG",
                  "destinationField": "KHSV",
                  "originNameField": "Cincinnati/NorthernKentuckyInternationalAirport",
                  "originCityField": "Hebron,KY",
                  "destinationNameField": "HuntsvilleIntl",
                  "destinationCityField": "Huntsville,AL"
                },
                {
                  "faFlightIDField": "LXJ430-1687153539-sw-1778p",
                  "identField": "LXJ430",
                  "aircrafttypeField": "E545",
                  "filed_eteField": "01:35:00",
                  "filed_timeField": 1687185669,
                  "filed_departuretimeField": 1687187700,
                  "filed_airspeed_ktsField": 446,
                  "filed_airspeed_machField": "",
                  "filed_altitudeField": 450,
                  "routeField": "LBYMEIDEVACFORKSPETES",
                  "actualdeparturetimeField": 1687189431,
                  "estimatedarrivaltimeField": 1687195556,
                  "actualarrivaltimeField": 1687195556,
                  "divertedField": "",
                  "originField": "KMSY",
                  "destinationField": "KCVG",
                  "originNameField": "NewOrleansIntl",
                  "originCityField": "NewOrleans,LA",
                  "destinationNameField": "Cincinnati/NorthernKentuckyInternationalAirport",
                  "destinationCityField": "Hebron,KY"
                }
              ]
            },
            "aircraftType": {
              "manufacturerField": "Embraer",
              "typeField": "Legacy450",
              "descriptionField": "twin-jet"
            },
            "inFlightInfo": {
              "faFlightIDField": "LXJ430-1687292631-sw-1007p",
              "identField": "LXJ430",
              "prefixField": "",
              "typeField": "E545",
              "suffixField": "",
              "originField": "KRDU",
              "destinationField": "TAPA",
              "timeoutField": "ok",
              "timestampField": 1687362787,
              "departureTimeField": 1687357091,
              "firstPositionTimeField": 1687357091,
              "arrivalTimeField": 0,
              "longitudeField": -73.37406,
              "latitudeField": 27.19013,
              "lowLongitudeField": -79.15694,
              "lowLatitudeField": 27.19013,
              "highLongitudeField": -73.37406,
              "highLatitudeField": 35.9151,
              "groundspeedField": 425,
              "altitudeField": 410,
              "headingField": 131,
              "altitudeStatusField": "",
              "updateTypeField": "TP",
              "altitudeChangeField": "",
              "waypointsField": ""
            },
            "originAirportInfo": {
              "nameField": "Raleigh-DurhamIntl",
              "locationField": "Raleigh/Durham,NC",
              "longitudeField": -78.7874756,
              "latitudeField": 35.87764,
              "timezoneField": ":America/New_York"
            },
            "destinationAirportInfo": {
              "nameField": "VCBirdInt'l",
              "locationField": "SaintJohn's,Antigua",
              "longitudeField": -61.7926674,
              "latitudeField": 17.13675,
              "timezoneField": ":America/Antigua"
            }
          }
        ],
        "errors": []
      },
      "statusCode": 200,
      "errors": [],
      "warnings": []
    },
    "id": 1,
    "status": 5,
    "isCanceled": false,
    "isCompleted": true,
    "isCompletedSuccessfully": true,
    "creationOptions": 0,
    "isFaulted": false
  }'
"@

$demoTripAggregate = '{
  "Message": "{\"Trip\":{\"TripID\":4721643,\"PublicTripID\":\"4cc6fd39-791d-4455-b4c7-e34478a6d22c\",\"TripTypeID\":1,\"TripNumber\":\"3536011\",\"RemarksJSON\":\"[{\\\"RemarkID\\\":6567143,\\\"RemarkTypeID\\\":1,\\\"PublicTripID\\\":\\\"4CC6FD39-791D-4455-B4C7-E34478A6D22C\\\",\\\"Remark\\\":\\\"KEWR \\\\/ FBO SIGNATURE FSO \\\\/ 00:00-23:59\\\\nKPHL \\\\/ FBO ATLANTIC AVIATION \\\\/ 00:00-23:59\\\",\\\"ActiveFlag\\\":true,\\\"CreatedByUsername\\\":\\\"Jared McCord\\\",\\\"CreatedDateUTC\\\":\\\"2023-06-29T21:09:10.180\\\",\\\"ModifiedByUsername\\\":\\\"Jared McCord\\\",\\\"ModifiedDateUTC\\\":\\\"2023-06-29T21:09:10.180\\\"}]\",\"ExternalTripID\":null,\"SentientTripID\":null,\"SentientFlightID\":null,\"SkynetQuoteID\":null,\"ActiveFlag\":true,\"IsDeletedFlag\":false,\"CreatedByUsername\":\"Jared McCord\",\"CreatedDateUTC\":\"2023-06-29T21:08:34.703\",\"ModifiedByUsername\":\"Jared McCord\",\"ModifiedDateUTC\":\"2023-06-29T21:08:34.703\"},\"Legs\":[{\"LegID\":4940551,\"PublicLegID\":\"464a10bc-0663-4877-a3f4-a573cb6b2eca\",\"TripID\":4721643,\"PublicTripID\":\"4cc6fd39-791d-4455-b4c7-e34478a6d22c\",\"LegTypeID\":2,\"ContractID\":0,\"FARPart\":\"91\",\"OperationalUpgradeDowngradeFlag\":false,\"GuaranteedUpgradeDowngradeFlag\":false,\"ServicesJSON\":\"[]\",\"RepositioningFlag\":false,\"IsInternalAircraftForExternalCharterFlag\":false,\"HandlingState\":0,\"HasServiceFlag\":false,\"DepartureSlotTimeUTC\":null,\"ArrivalSlotTimeUTC\":null,\"AvailableToSellFlag\":true,\"LegRemarks\":null,\"IsPilotLegalityUnconfirmedForLEONFlag\":false,\"ParentContract\":\"FLTOP\",\"IsHighRiskContractFlag\":false,\"RequiresManualBillingFlag\":false,\"InterchangeFlag\":false,\"InterchangeApprovalFlag\":false,\"ContractJSON\":\"{\\\"LegacyParentContractID\\\":236,\\\"ParentContractCode\\\":\\\"FLTOP\\\",\\\"LegacyChildContractID\\\":395,\\\"ChildContractCode\\\":\\\"FLTOP\\\",\\\"Name\\\":null,\\\"Description\\\":\\\"Non Billable\\\",\\\"TeamAssignmentID\\\":34,\\\"TeamDescription\\\":\\\"Repositions\\\",\\\"SalesDirector\\\":null,\\\"SalesDirectorEmail\\\":null,\\\"ContractStatus\\\":\\\"0\\\",\\\"ChildContractStipulations\\\":null,\\\"ContractFARPart\\\":\\\"135\\\",\\\"AccountType\\\":null,\\\"FoiavifsCompanyID\\\":1}\",\"LegOverrideJSON\":\"{}\",\"LegExperienceJSON\":\"{}\",\"RequestedAircraft\":\"\",\"SchedulerID\":1,\"OwnerID\":1,\"OrdersJSON\":\"[]\",\"OrderDetailsJSON\":\"[]\",\"GroundTransportationJSON\":\"[{\\\"TRIPLOGISTICS_ID\\\":\\\"3335421.DB1\\\",\\\"POD_FBO_ID\\\":\\\"1114.MGR\\\",\\\"POA_FBO_ID\\\":\\\"1949.MGR\\\",\\\"HANDLING\\\":\\\"\\\",\\\"HANDLING_PHONE\\\":\\\"\\\",\\\"HANDLING_TLX\\\":\\\"\\\",\\\"HANDLING_FRQ\\\":\\\"\\\",\\\"HANDLING_FAX\\\":\\\"\\\",\\\"TRIPLEG_ID\\\":\\\"3328643.OPT\\\",\\\"CREW_HOTEL\\\":\\\"\\\",\\\"CREW_PHONE\\\":\\\"\\\",\\\"CREW_CONTACT\\\":\\\"\\\",\\\"CREW_CONFIRM\\\":\\\"\\\",\\\"CUSTOMS_ID\\\":\\\"0\\\",\\\"CUSTOMS_REMARKS\\\":\\\"\\\",\\\"POD_FBO_REMARKS\\\":\\\"\\\",\\\"POA_FBO_REMARKS\\\":\\\"\\\",\\\"HANDLING_REMAKRS\\\":null,\\\"CREW_REMARKS\\\":\\\"\\\",\\\"PAX_REMARKS\\\":\\\"\\\",\\\"CONTACTS_REMARKS\\\":\\\"\\\",\\\"CATERING_REMARKS\\\":\\\"\\\",\\\"TRANSPORT_REMARKS\\\":\\\"\\\",\\\"MODIFIED_BY_USER_ID\\\":\\\"7347.DB1\\\",\\\"STATUS\\\":\\\"0\\\",\\\"CATERING_AMOUNT\\\":null,\\\"CREWAIRPORTHOTEL_ID\\\":\\\"0\\\",\\\"PAXAIRPORTHOTEL_ID\\\":\\\"0\\\",\\\"UseShortLegWaiver\\\":\\\"0\\\",\\\"PAXDropOff\\\":\\\"0\\\",\\\"PaxPickUp\\\":\\\"0\\\",\\\"CustomsStop\\\":\\\"0\\\",\\\"FuelStop\\\":\\\"0\\\",\\\"FourtyEightHourDiscount\\\":null,\\\"EMAIL_RECIPIENTS\\\":null,\\\"PaxStop\\\":null,\\\"SkynetLegID\\\":4217352,\\\"SkynetPublicLegID\\\":\\\"464a10bc-0663-4877-a3f4-a573cb6b2eca\\\"}]\",\"ActiveFlag\":true,\"IsDeletedFlag\":false,\"CreatedByUsername\":\"Jared McCord\",\"CreatedDateUTC\":\"2023-06-29T21:08:39.993\",\"ModifiedByUsername\":\"Jared McCord\",\"ModifiedDateUTC\":\"2023-06-29T21:08:39.993\"}],\"LegDetails\":[{\"LegDetailID\":6065481,\"PublicLegDetailID\":\"4ee96034-4ce3-47ee-9698-d8436666c8b9\",\"LegID\":4940551,\"PublicLegID\":\"464a10bc-0663-4877-a3f4-a573cb6b2eca\",\"LegDetailTypeID\":2,\"ArrivalAirportID\":5264,\"ArrivalDateLocal\":\"2023-06-30T10:00:00\",\"ArrivalDateUTC\":\"2023-06-30T14:00:00\",\"ArrivalAirportJSON\":\"{\\\"ICAO\\\":\\\"KPHL \\\",\\\"IATA\\\":\\\"PHL\\\",\\\"FAACode\\\":\\\"PHL\\\",\\\"IsMountainousFlag\\\":false,\\\"CountryID\\\":237,\\\"UTCTime\\\":\\\"2023-06-30T14:00:00\\\",\\\"LocalTime\\\":\\\"2023-06-30T10:00:00\\\",\\\"Timezone\\\":{\\\"TimezoneID\\\":\\\"America/New_York\\\",\\\"TimezoneName\\\":\\\"110\\\",\\\"Abbreviation\\\":\\\"EDT\\\",\\\"DSTOffset\\\":1.0,\\\"RawOffset\\\":-5.0},\\\"FBO\\\":{\\\"LegacyFBOID\\\":null,\\\"AirportID\\\":0,\\\"Name\\\":null,\\\"Email\\\":null,\\\"Remarks\\\":null}}\",\"DepartureAirportID\":4768,\"DepartureDateLocal\":\"2023-06-30T09:32:00\",\"DepartureDateUTC\":\"2023-06-30T13:32:00\",\"DepartureAirportJSON\":\"{\\\"ICAO\\\":\\\"KEWR \\\",\\\"IATA\\\":\\\"EWR\\\",\\\"FAACode\\\":\\\"EWR\\\",\\\"IsMountainousFlag\\\":false,\\\"CountryID\\\":237,\\\"UTCTime\\\":\\\"2023-06-30T13:32:00\\\",\\\"LocalTime\\\":\\\"2023-06-30T09:32:00\\\",\\\"Timezone\\\":{\\\"TimezoneID\\\":\\\"America/New_York\\\",\\\"TimezoneName\\\":\\\"110\\\",\\\"Abbreviation\\\":\\\"EDT\\\",\\\"DSTOffset\\\":1.0,\\\"RawOffset\\\":-5.0},\\\"FBO\\\":{\\\"LegacyFBOID\\\":null,\\\"AirportID\\\":0,\\\"Name\\\":null,\\\"Email\\\":null,\\\"Remarks\\\":null}}\",\"AircraftJSON\":\"{\\\"CacheAircraftID\\\":154,\\\"AircraftID\\\":154,\\\"PublicAircraftID\\\":\\\"634478d3-37e6-4dda-b402-f96a4fda09ac\\\",\\\"AircraftTypeID\\\":10,\\\"AircraftType\\\":\\\"EMB-505/G1000\\\",\\\"TailNumber\\\":\\\"N360FX\\\",\\\"MaxSeats\\\":7.0,\\\"Make\\\":\\\"Embraer\\\",\\\"ModelName\\\":\\\"EMB-505\\\",\\\"MaxGrossTakeoffWeight\\\":17968.00,\\\"CompanyID\\\":\\\"3\\\",\\\"CompanyName\\\":\\\"Flexjet\\\",\\\"CallSign\\\":\\\"N360FX\\\",\\\"HoldingFile\\\":false}\",\"CrewJSON\":\"[]\",\"LegTrackingStatus\":0,\"PassengersJSON\":\"[]\",\"BlockTimeOutUTC\":null,\"BlockTimeOutLocal\":null,\"BlockTimeInUTC\":null,\"BlockTimeInLocal\":null,\"ActiveFlag\":true,\"IsDeletedFlag\":false,\"CreatedByUsername\":\"Jared McCord\",\"CreatedDateUTC\":\"2023-06-29T21:08:50.303\",\"ModifiedByUsername\":\"Jared McCord\",\"ModifiedDateUTC\":\"2023-06-29T21:08:50.303\"},{\"LegDetailID\":6065482,\"PublicLegDetailID\":\"649e0e07-4ca2-49ab-b59e-f81990e58c3b\",\"LegID\":4940551,\"PublicLegID\":\"464a10bc-0663-4877-a3f4-a573cb6b2eca\",\"LegDetailTypeID\":3,\"ArrivalAirportID\":5264,\"ArrivalDateLocal\":\"2023-06-30T10:00:00\",\"ArrivalDateUTC\":\"2023-06-30T14:00:00\",\"ArrivalAirportJSON\":\"{\\\"ICAO\\\":\\\"KPHL \\\",\\\"IATA\\\":\\\"PHL\\\",\\\"FAACode\\\":\\\"PHL\\\",\\\"IsMountainousFlag\\\":false,\\\"CountryID\\\":237,\\\"UTCTime\\\":\\\"2023-06-30T14:00:00\\\",\\\"LocalTime\\\":\\\"2023-06-30T10:00:00\\\",\\\"Timezone\\\":{\\\"TimezoneID\\\":\\\"America/New_York\\\",\\\"TimezoneName\\\":\\\"110\\\",\\\"Abbreviation\\\":\\\"EDT\\\",\\\"DSTOffset\\\":1.0,\\\"RawOffset\\\":-5.0},\\\"FBO\\\":{\\\"LegacyFBOID\\\":\\\"1949.MGR\\\",\\\"AirportID\\\":0,\\\"Name\\\":\\\"ATLANTIC AVIATION\\\",\\\"Email\\\":\\\"PHLFRONTDESK@ATLANTICAVIATION.COM\\\",\\\"Remarks\\\":\\\"Use World Fuel Contract Fuel to pay at this location effective  11/02/09...bpeters\\\\r\\\\n\\\\r\\\\nDo Not Advise Arrivals and Departures.\\\\r\\\\n\\\\r\\\\nNo O2 Svc!!!\\\\r\\\\n\\\"}}\",\"DepartureAirportID\":4768,\"DepartureDateLocal\":\"2023-06-30T09:32:00\",\"DepartureDateUTC\":\"2023-06-30T13:32:00\",\"DepartureAirportJSON\":\"{\\\"ICAO\\\":\\\"KEWR \\\",\\\"IATA\\\":\\\"EWR\\\",\\\"FAACode\\\":\\\"EWR\\\",\\\"IsMountainousFlag\\\":false,\\\"CountryID\\\":237,\\\"UTCTime\\\":\\\"2023-06-30T13:32:00\\\",\\\"LocalTime\\\":\\\"2023-06-30T09:32:00\\\",\\\"Timezone\\\":{\\\"TimezoneID\\\":\\\"America/New_York\\\",\\\"TimezoneName\\\":\\\"110\\\",\\\"Abbreviation\\\":\\\"EDT\\\",\\\"DSTOffset\\\":1.0,\\\"RawOffset\\\":-5.0},\\\"FBO\\\":{\\\"LegacyFBOID\\\":\\\"1114.MGR\\\",\\\"AirportID\\\":0,\\\"Name\\\":\\\"SIGNATURE FSO\\\",\\\"Email\\\":\\\"Newark@Signatureflight.com\\\",\\\"Remarks\\\":\\\"no O2!!!\\\\r\\\\n\\\\r\\\\nAVIS CARS AT FBO\\\"}}\",\"AircraftJSON\":\"{\\\"CacheAircraftID\\\":154,\\\"AircraftID\\\":154,\\\"PublicAircraftID\\\":\\\"634478d3-37e6-4dda-b402-f96a4fda09ac\\\",\\\"AircraftTypeID\\\":10,\\\"AircraftType\\\":\\\"EMB-505/G1000\\\",\\\"TailNumber\\\":\\\"N360FX\\\",\\\"MaxSeats\\\":7.0,\\\"Make\\\":\\\"Embraer\\\",\\\"ModelName\\\":\\\"EMB-505\\\",\\\"MaxGrossTakeoffWeight\\\":17968.00,\\\"CompanyID\\\":\\\"3\\\",\\\"CompanyName\\\":\\\"Flexjet\\\",\\\"CallSign\\\":\\\"N360FX\\\",\\\"HoldingFile\\\":false}\",\"CrewJSON\":\"[{\\\"ContactID\\\":570824,\\\"Alias\\\":\\\"FREY\\\",\\\"FirstName\\\":\\\"BRETT\\\",\\\"LastName\\\":\\\"FREY\\\",\\\"Seat\\\":\\\"P\\\",\\\"DOB\\\":\\\"1967-09-13T00:00:00\\\",\\\"PassportNumber\\\":\\\"654181331\\\",\\\"PassportExpiryDate\\\":\\\"2030-01-30T00:00:00\\\",\\\"Citizenship\\\":\\\"US\\\",\\\"License\\\":\\\"3102781\\\",\\\"ModifiedByUsername\\\":\\\"Jared McCord\\\",\\\"ModifiedDate\\\":\\\"2023-06-29T17:06:47.733\\\"},{\\\"ContactID\\\":938746,\\\"Alias\\\":\\\"CANT\\\",\\\"FirstName\\\":\\\"VICTOR\\\",\\\"LastName\\\":\\\"CANTIN\\\",\\\"Seat\\\":\\\"S\\\",\\\"DOB\\\":\\\"1979-01-11T00:00:00\\\",\\\"PassportNumber\\\":\\\"668078977\\\",\\\"PassportExpiryDate\\\":\\\"2031-05-23T00:00:00\\\",\\\"Citizenship\\\":\\\"US\\\",\\\"License\\\":\\\"4319597\\\",\\\"ModifiedByUsername\\\":\\\"Jared McCord\\\",\\\"ModifiedDate\\\":\\\"2023-06-29T17:06:47.74\\\"}]\",\"LegTrackingStatus\":0,\"PassengersJSON\":\"[]\",\"BlockTimeOutUTC\":null,\"BlockTimeOutLocal\":null,\"BlockTimeInUTC\":null,\"BlockTimeInLocal\":null,\"ActiveFlag\":true,\"IsDeletedFlag\":false,\"CreatedByUsername\":\"Jared McCord\",\"CreatedDateUTC\":\"2023-06-29T21:08:51.35\",\"ModifiedByUsername\":\"Jared McCord\",\"ModifiedDateUTC\":\"2023-06-29T21:09:19.237\"},{\"LegDetailID\":6067276,\"PublicLegDetailID\":\"fd849ddb-1b0a-45f0-b2de-3c24c0360475\",\"LegID\":4940551,\"PublicLegID\":\"464a10bc-0663-4877-a3f4-a573cb6b2eca\",\"LegDetailTypeID\":6,\"ArrivalAirportID\":5264,\"ArrivalDateLocal\":\"2023-06-30T10:00:00\",\"ArrivalDateUTC\":\"2023-06-30T14:00:00\",\"ArrivalAirportJSON\":\"{\\\"ICAO\\\":\\\"KPHL \\\",\\\"IATA\\\":\\\"PHL\\\",\\\"FAACode\\\":\\\"PHL\\\",\\\"IsMountainousFlag\\\":false,\\\"CountryID\\\":237,\\\"UTCTime\\\":\\\"2023-06-30T14:00:00\\\",\\\"LocalTime\\\":\\\"2023-06-30T10:00:00\\\",\\\"Timezone\\\":{\\\"TimezoneID\\\":\\\"America/New_York\\\",\\\"TimezoneName\\\":\\\"110\\\",\\\"Abbreviation\\\":\\\"EDT\\\",\\\"DSTOffset\\\":1.0,\\\"RawOffset\\\":-5.0},\\\"FBO\\\":{\\\"LegacyFBOID\\\":\\\"1949.MGR\\\",\\\"AirportID\\\":0,\\\"Name\\\":\\\"ATLANTIC AVIATION\\\",\\\"Email\\\":\\\"PHLFRONTDESK@ATLANTICAVIATION.COM\\\",\\\"Remarks\\\":\\\"Use World Fuel Contract Fuel to pay at this location effective  11/02/09...bpeters\\\\r\\\\n\\\\r\\\\nDo Not Advise Arrivals and Departures.\\\\r\\\\n\\\\r\\\\nNo O2 Svc!!!\\\\r\\\\n\\\"}}\",\"DepartureAirportID\":4768,\"DepartureDateLocal\":\"2023-06-30T09:32:00\",\"DepartureDateUTC\":\"2023-06-30T13:32:00\",\"DepartureAirportJSON\":\"{\\\"ICAO\\\":\\\"KEWR \\\",\\\"IATA\\\":\\\"EWR\\\",\\\"FAACode\\\":\\\"EWR\\\",\\\"IsMountainousFlag\\\":false,\\\"CountryID\\\":237,\\\"UTCTime\\\":\\\"2023-06-30T13:32:00\\\",\\\"LocalTime\\\":\\\"2023-06-30T09:32:00\\\",\\\"Timezone\\\":{\\\"TimezoneID\\\":\\\"America/New_York\\\",\\\"TimezoneName\\\":\\\"110\\\",\\\"Abbreviation\\\":\\\"EDT\\\",\\\"DSTOffset\\\":1.0,\\\"RawOffset\\\":-5.0},\\\"FBO\\\":{\\\"LegacyFBOID\\\":\\\"1114.MGR\\\",\\\"AirportID\\\":0,\\\"Name\\\":\\\"SIGNATURE FSO\\\",\\\"Email\\\":\\\"Newark@Signatureflight.com\\\",\\\"Remarks\\\":\\\"no O2!!!\\\\r\\\\n\\\\r\\\\nAVIS CARS AT FBO\\\"}}\",\"AircraftJSON\":\"{\\\"CacheAircraftID\\\":154,\\\"AircraftID\\\":154,\\\"PublicAircraftID\\\":\\\"634478d3-37e6-4dda-b402-f96a4fda09ac\\\",\\\"AircraftTypeID\\\":10,\\\"AircraftType\\\":\\\"EMB-505/G1000\\\",\\\"TailNumber\\\":\\\"N360FX\\\",\\\"MaxSeats\\\":7.0,\\\"Make\\\":\\\"Embraer\\\",\\\"ModelName\\\":\\\"EMB-505\\\",\\\"MaxGrossTakeoffWeight\\\":17968.00,\\\"CompanyID\\\":\\\"3\\\",\\\"CompanyName\\\":\\\"Flexjet\\\",\\\"CallSign\\\":\\\"N360FX\\\",\\\"HoldingFile\\\":false}\",\"CrewJSON\":\"[{\\\"ContactID\\\":570824,\\\"Alias\\\":\\\"FREY\\\",\\\"FirstName\\\":\\\"BRETT\\\",\\\"LastName\\\":\\\"FREY\\\",\\\"Seat\\\":\\\"P\\\",\\\"DOB\\\":\\\"1967-09-13T00:00:00\\\",\\\"PassportNumber\\\":\\\"654181331\\\",\\\"PassportExpiryDate\\\":\\\"2030-01-30T00:00:00\\\",\\\"Citizenship\\\":\\\"US\\\",\\\"License\\\":\\\"3102781\\\",\\\"ModifiedByUsername\\\":\\\"Jared McCord\\\",\\\"ModifiedDate\\\":\\\"2023-06-29T17:06:47.733\\\"},{\\\"ContactID\\\":938746,\\\"Alias\\\":\\\"CANT\\\",\\\"FirstName\\\":\\\"VICTOR\\\",\\\"LastName\\\":\\\"CANTIN\\\",\\\"Seat\\\":\\\"S\\\",\\\"DOB\\\":\\\"1979-01-11T00:00:00\\\",\\\"PassportNumber\\\":\\\"668078977\\\",\\\"PassportExpiryDate\\\":\\\"2031-05-23T00:00:00\\\",\\\"Citizenship\\\":\\\"US\\\",\\\"License\\\":\\\"4319597\\\",\\\"ModifiedByUsername\\\":\\\"Jared McCord\\\",\\\"ModifiedDate\\\":\\\"2023-06-29T17:06:47.74\\\"}]\",\"LegTrackingStatus\":0,\"PassengersJSON\":\"[]\",\"BlockTimeOutUTC\":null,\"BlockTimeOutLocal\":null,\"BlockTimeInUTC\":null,\"BlockTimeInLocal\":null,\"ActiveFlag\":true,\"IsDeletedFlag\":false,\"CreatedByUsername\":\"TripAPI\",\"CreatedDateUTC\":\"2023-06-30T12:07:32.32\",\"ModifiedByUsername\":\"TripAPI\",\"ModifiedDateUTC\":\"2023-06-30T12:07:32.32\"}],\"TripPackage\":null,\"UpdatedEntity\":2,\"UpdatedEntityTypeID\":6,\"UpdatedEntityID\":\"fd849ddb-1b0a-45f0-b2de-3c24c0360475\"}",
  "MessageGuid": "ef90561c-8fa0-4d52-bb81-4a0599e2240b",
  "Title": "TripAggregate",
  "Action": 4,
  "IsFromSkynet": false,
  "MessageState": 0,
  "Error": null,
  "CompressionType": 0,
  "EntityType": null,
  "EntityID": null,
  "ParentEntityType": null,
  "ParentEntityID": null
}'

$demoAircraft = '{
  "Message": {
    "AircraftID": 288,
    "PublicAircraftID": "763fcd54-e516-44d9-bb40-8b75a5199087",
    "BusinessUnitID": 3,
    "BaseAirportICAO": "KBOS ",
    "TypeID": 282,
    "IsType": false,
    "TypeName": "Sen Light Jet",
    "TailNumber": "Sen Light Jet",
    "SerialNumber": null,
    "HoldingFile": true,
    "Make": null,
    "ModelName": null,
    "MaxSeats": 7.0,
    "MinRunwayLength": 4200.0,
    "MinRunwayWidth": 75.0,
    "Colors": null,
    "ExternalTrim": null,
    "CabinSize": "SMALL",
    "CabinType": null,
    "Speed": 360.0,
    "Endurance": 0.0,
    "Class": "75",
    "AircraftGroup": "3",
    "Cat": null,
    "SatCM": false,
    "LRNav": false,
    "LandingReserves": null,
    "MarDateInd": false,
    "QualifyingType": "EMB-505",
    "DecalNumber": null,
    "InspectionProgram": null,
    "OverflightAllowed": false,
    "EmptyWeight": null,
    "MaxZeroFuelWeight": null,
    "SelCalNumber": null,
    "MaxGrossTakeoffWeight": null,
    "LandingWeight": null,
    "MaxFuel": null,
    "MultiServiceCardNumber": null,
    "DecalExpirationDate": "2023-07-07T00:00:00",
    "AlternateTailNumber": null,
    "CurrentLocationICAO": "KCMA",
    "AirWorthinessDate": "2023-07-07T00:00:00",
    "CertificationDate": "2023-07-07T00:00:00",
    "ExcludeFromGantt": true,
    "CockpitWeight": null,
    "InsuranceExpiredFlag": null,
    "Notes": "",
    "IsManagedFlag": false,
    "HasBeltedLavatory": false,
    "PaxWeight": null,
    "LegacyPhoneType": null,
    "LegacyPhoneNumber": null,
    "FAAFireCategoryCode": null,
    "IATAFireCategoryId": null,
    "IsACARSCapableFlag": false,
    "FleetType": null,
    "IsRedLabelFlag": false,
    "AircraftCompany": "Sentient Jet",
    "RowAssignment": null,
    "LiveRate": null,
    "DeadRate": null,
    "FuelSurcharge": null,
    "Landing": null,
    "DomesticRON": null,
    "DailyMinimumHours": null,
    "EffectiveDate": "2023-07-07T00:00:00",
    "ActiveFlag": true,
    "IsDeletedFlag": false,
    "CreatedByUsername": "Rudnickas, Kim",
    "CreatedDateUTC": "2022-07-26T16:59:13.15",
    "ModifiedByUsername": "Davis, Jim ",
    "ModifiedDateUTC": "2023-07-07T19:38:23.32"
  },
  "MessageGuid": "2dd243ac-12b9-4f2e-8a72-e59abd140f9d",
  "Title": "Aircraft",
  "Action": 4,
  "IsFromSkynet": false,
  "MessageState": 0,
  "Error": null,
  "CompressionType": 0,
  "EntityType": null,
  "EntityID": null,
  "ParentEntityType": null,
  "ParentEntityID": null
}'